export const ROUTES = {
  home: "/",
  women: "/women",
  men: "/men",
  newIn: "/new-in",
  collections: "/collections",
  collection: (slug: string) => `/collections/${slug}`,
  sale: "/sale",
  journal: "/journal",
  journalPost: (slug: string) => `/journal/${slug}`,
  about: "/about",
  wishlist: "/wishlist",
  account: "/account",
  cart: "/cart",
  product: (slug: string) => `/products/${slug}`,
  admin: "/admin",
  sustainability: "/sustainability",
  careers: "/careers",
  contact: "/contact",
  shippingReturns: "/shipping-returns",
  sizeGuide: "/size-guide",
  faq: "/faq",
  legal: (slug: string) => `/legal/${slug}`,
} as const;
