export interface BreadcrumbItem {
  name: string;
  href: string;
}

export interface FaqItem {
  question: string;
  answer: string;
}

export interface SiteSeoDefaults {
  titleTemplate: string;
  defaultTitle: string;
  defaultDescription: string;
  siteUrl: string;
  /**
   * Optional. Leave it unset to use the branded card generated by `app/opengraph-image.tsx`
   * — setting a value here overrides that card everywhere, which is not obvious from the
   * field name. Only set it to point at a specific image you want shared instead.
   */
  defaultOgImage?: string;
  twitterHandle?: string;
  organization: {
    name: string;
    logo: string;
    sameAs: string[];
  };
}
